### ISSUE TITLE
[RELEASE ISSUE]: Checklist for next release of cif_core

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/cif_core#317]
This is a first attempt at a release checklist. We do have some things unresolved, but we'll try and deal with those as they arise. I can be release manager this time as we iron out the problems, hopefully we can rotate around.

- [x] Release manager appointed
- [x] `_dictionary_audit.revision` comments summarised
- [x] Release branch created
- [x] Next version placeholder created in dictionary_audit section in master branch
- [x] Plain text summary of changes created (ideally automatic Github changeset comments)
- [x] cif_core mailing list advised
- [x] ccp4 mailing list advised
- [x] All comments/issues arising during review period addressed (add to list below)
- [x] Final DOI and URL edited into file (IUCr Chester office to advise of DOI)
- [x] Github release tagged
- [x] Zenodo/IUCr updated with released file

Outstanding pull requests/ issues that should be resolved before releasing. Only the very easy ones go here, e.g. 'janitorial'. Please check any issues you have raised and see if they could be resolved easily or have already been resolved.

- [x] #312 
- [x] #358 
- [x] #103 
- [x] #361

**Comment by jamesrhester** [comment]
Release manager is @jamesrhester this time.

**Comment by vaitkus** [comment]
One question regarding the summarisation of `_dictionary_audit.revision` comments. Given that the last properly tagged version of `CIF_CORE` was 3.0.13, should all other versions (3.0.14, 3.1.0 and 3.2.0) be combined into a single new version 3.2.0 before release?

**Comment by jamesrhester** [comment]
What I planned to do is summarise the comments within each `_dictionary_audit.revision` for those three versions, without actually merging them into a single version. The plain text summary would include changes from all of those three versions.

My thinking is that the dictionary audit information doesn't have to have details of all bug fixes, minor typo corrections and so on, these can just be described as "bug and typo fixes". The nature of each change will be available in the git history. More important to keep are things like new categories being added.

**Comment by jamesrhester** [comment]
I have created an initial set of release notes in the wiki [here](https://github.com/COMCIFS/cif_core/wiki/Release-Notes-for-CIF-CORE-3.2.0). Please look over them and add anything you think is missing, bearing in mind that we don't want them to be so long that we lose the attention of busy software authors. @rowlesmr would you mind writing up the section on elemental composition? You could include a link to the example contained in the file.

**Comment by rowlesmr** [comment]
I've added some words and links.

**Comment by jamesrhester** [comment]
Excellent!

**Comment by jamesrhester** [comment]
I've confirmed with the IUCr Chester office that they will create a DOI for us using CrossRef, and the form of the DOI will be known ahead of time so that we can edit it in. It will also refer to the actual file, rather than a landing page.

**Comment by publcif** [comment]
I've been asked today "Why not distribute a single dictionary file?" - i.e. expanded version including imports. Any thoughts on this?

**Comment by vaitkus** [comment]
Would this also be extended to cases where dictionaries import other dictionaries?

**Comment by jamesrhester** [comment]
I've now placed the release files on Github and can say we have finally finished the 3.2.0 release.
